# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: pre-merge tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: psf/black@stable
      - uses: isort/isort-action@v1
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"
      - name: Install Poetry
        uses: snok/install-poetry@v1
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          poetry install
          playwright install
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Test with pytest
        run: |
          pytest -v
      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-traces
          path: test-results/
      - name: Store Playwright Traces and Videos From Failed Tests
        if: failure()
        uses: actions/upload-artifact@v4
        id: artifact-upload-step
        with:
          name: test-results
          path: test-results/
          retention-days: 7
      - name: Link Playwright Traces And Videos To Allure Report
        working-directory: allure-results
        if: failure()
        run: echo ARTIFACT_URL=${{ steps.artifact-upload-step.outputs.artifact-url }} >> environment.properties
      - name: Link Git Information And Browser Version To Allure Report
        working-directory: allure-results
        if: always()
        run: |
          {
           echo BUILD_URL=${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
           echo GIT_BRANCH=${{ github.head_ref || github.ref_name }}
           echo GIT_COMMIT_ID=${{ github.sha }}
           echo GIT_COMMIT_MESSAGE=$(git show -s --format=%s HEAD)
           echo GIT_COMMIT_AUTHOR_NAME=$(git show -s --format='%ae' HEAD)
           echo GIT_COMMIT_TIME=$(git show -s --format=%ci HEAD)
           echo CHROME_VERSION=$(google-chrome --product-version)
          } >> environment.properties
      - name: Generate Allure Report
        uses: simple-elf/allure-report-action@master
        if: always()
        id: allure-report
        with:
          allure_results: allure-results
          allure_report: allure-report
          gh_pages: gh-pages
          allure_history: allure-history
# pip install flake8 pytest playwright pandas pytest-playwright openpyxl allure-pytest
